# Generated by Django 4.1.3 on 2022-11-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formfillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('dept_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('provost_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('register_signature', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d')),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(default=' ', max_length=50, verbose_name='Phone')),
                ('father', models.CharField(default='', max_length=200, verbose_name='Father/Husband')),
                ('mother', models.CharField(default='', max_length=200, verbose_name='Mother')),
                ('guardian', models.CharField(default='', max_length=200, verbose_name='Guardian')),
                ('village', models.CharField(default='', max_length=200, verbose_name='Village')),
                ('post_office', models.CharField(default='', max_length=200, verbose_name='Post office')),
                ('upazila', models.CharField(default='', max_length=200, verbose_name='Upazila')),
                ('district', models.CharField(default='', max_length=200, verbose_name='district')),
                ('birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date')),
                ('student_id', models.CharField(max_length=200, verbose_name='Student ID')),
                ('session', models.CharField(max_length=50, verbose_name='session')),
                ('semester', models.CharField(default='', max_length=50, verbose_name='semester')),
                ('hall', models.CharField(default='', max_length=200, verbose_name='hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
