# Generated by Django 4.1.3 on 2022-11-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='department',
            field=models.CharField(default='', max_length=200, verbose_name='department'),
        ),
    ]
