# Generated by Django 4.1.3 on 2022-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_formfillup_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='exam_year',
            field=models.CharField(default='', max_length=50, verbose_name='exam_year'),
        ),
    ]
