# Generated by Django 4.1.3 on 2022-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formfillup_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='exam_starting_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date'),
        ),
    ]
