# Generated by Django 4.1.3 on 2022-11-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_formfillup_nationality_alter_formfillup_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='religion',
            field=models.CharField(default='', max_length=200, verbose_name='religion'),
        ),
    ]
