# Generated by Django 4.1.3 on 2022-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_formfillup_post_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfillup',
            name='student_id',
            field=models.CharField(max_length=200, verbose_name='student_id'),
        ),
    ]
